apiVersion: v1
kind: Service
metadata:
  name: pes2ug23cs925-service
  namespace: pes2ug23cs925-beta
spec:
  type: ClusterIP
  selector:
    app: nginx       # must match pod labels
  ports:
    - port: 80        # Service port
      targetPort: 80  # Container port
